<?php

namespace Database\Seeders;

use App\Models\Theme;
use Illuminate\Database\Seeder;

class ThemeSeeder extends Seeder
{
    public function run(): void
    {
        $themes = [

            // ── SaaS (7) ──────────────────────────────────────────────────────
            [
                'name'     => 'Apex SaaS',
                'slug'     => 'apex-saas',
                'category' => 'saas',
                'config'   => [
                    'layout'          => 'dashboard',
                    'primary_color'   => '#0f0f23',
                    'secondary_color' => '#7c3aed',
                    'font_heading'    => 'Space Grotesk',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-lg',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'glass',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'CloudDeck',
                'slug'     => 'cloud-deck',
                'category' => 'saas',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#0ea5e9',
                    'secondary_color' => '#06b6d4',
                    'font_heading'    => 'Plus Jakarta Sans',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-xl',
                    'hero_variant'    => 'split',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'normal',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'LaunchPad Pro',
                'slug'     => 'launchpad-pro',
                'category' => 'saas',
                'config'   => [
                    'layout'          => 'contemporary',
                    'primary_color'   => '#4f46e5',
                    'secondary_color' => '#f59e0b',
                    'font_heading'    => 'Sora',
                    'font_body'       => 'DM Sans',
                    'button_radius'   => 'rounded-full',
                    'hero_variant'    => 'video',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'outline',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'Metric Flow',
                'slug'     => 'metric-flow',
                'category' => 'saas',
                'config'   => [
                    'layout'          => 'grid',
                    'primary_color'   => '#1e293b',
                    'secondary_color' => '#10b981',
                    'font_heading'    => 'IBM Plex Sans',
                    'font_body'       => 'IBM Plex Sans',
                    'button_radius'   => 'rounded-md',
                    'hero_variant'    => 'image-right',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'compact',
                    'card_style'      => 'flat',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'SaaSify',
                'slug'     => 'saasify',
                'category' => 'saas',
                'config'   => [
                    'layout'          => 'minimal',
                    'primary_color'   => '#0d9488',
                    'secondary_color' => '#f43f5e',
                    'font_heading'    => 'Outfit',
                    'font_body'       => 'Outfit',
                    'button_radius'   => 'rounded-2xl',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'VaultOS',
                'slug'     => 'vault-os',
                'category' => 'saas',
                'config'   => [
                    'layout'          => 'dashboard',
                    'primary_color'   => '#0d1b2a',
                    'secondary_color' => '#d4a017',
                    'font_heading'    => 'JetBrains Mono',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-sm',
                    'hero_variant'    => 'split',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'compact',
                    'card_style'      => 'outline',
                    'footer_style'    => 'minimal',
                ],
            ],
            [
                'name'     => 'Orbit Platform',
                'slug'     => 'orbit-platform',
                'category' => 'saas',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#312e81',
                    'secondary_color' => '#fb923c',
                    'font_heading'    => 'Manrope',
                    'font_body'       => 'Manrope',
                    'button_radius'   => 'rounded-xl',
                    'hero_variant'    => 'carousel',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'normal',
                    'card_style'      => 'glass',
                    'footer_style'    => 'multi-column',
                ],
            ],

            // ── Ecommerce (7) ─────────────────────────────────────────────────
            [
                'name'     => 'ShopElite',
                'slug'     => 'shop-elite',
                'category' => 'ecommerce',
                'config'   => [
                    'layout'          => 'grid',
                    'primary_color'   => '#0a0a0a',
                    'secondary_color' => '#b8860b',
                    'font_heading'    => 'Cormorant Garamond',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-none',
                    'hero_variant'    => 'image-left',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'Luxe Cart',
                'slug'     => 'luxe-cart',
                'category' => 'ecommerce',
                'config'   => [
                    'layout'          => 'minimal',
                    'primary_color'   => '#fdf6ec',
                    'secondary_color' => '#c2185b',
                    'font_heading'    => 'Libre Baskerville',
                    'font_body'       => 'Lato',
                    'button_radius'   => 'rounded-full',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'Pixel Market',
                'slug'     => 'pixel-market',
                'category' => 'ecommerce',
                'config'   => [
                    'layout'          => 'contemporary',
                    'primary_color'   => '#7b2ff7',
                    'secondary_color' => '#f9e000',
                    'font_heading'    => 'Space Grotesk',
                    'font_body'       => 'Space Grotesk',
                    'button_radius'   => 'rounded-lg',
                    'hero_variant'    => 'video',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'compact',
                    'card_style'      => 'glass',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'StoreFront Pro',
                'slug'     => 'storefront-pro',
                'category' => 'ecommerce',
                'config'   => [
                    'layout'          => 'classic',
                    'primary_color'   => '#1a3a5c',
                    'secondary_color' => '#e74c3c',
                    'font_heading'    => 'Roboto Slab',
                    'font_body'       => 'Roboto',
                    'button_radius'   => 'rounded-md',
                    'hero_variant'    => 'carousel',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'normal',
                    'card_style'      => 'outline',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'NovaBuy',
                'slug'     => 'nova-buy',
                'category' => 'ecommerce',
                'config'   => [
                    'layout'          => 'grid',
                    'primary_color'   => '#1a0533',
                    'secondary_color' => '#84cc16',
                    'font_heading'    => 'Clash Display',
                    'font_body'       => 'DM Sans',
                    'button_radius'   => 'rounded-xl',
                    'hero_variant'    => 'split',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'normal',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'CraftMart',
                'slug'     => 'craft-mart',
                'category' => 'ecommerce',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#5c3317',
                    'secondary_color' => '#f97316',
                    'font_heading'    => 'Playfair Display',
                    'font_body'       => 'Source Sans Pro',
                    'button_radius'   => 'rounded-sm',
                    'hero_variant'    => 'image-right',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'DropZone',
                'slug'     => 'drop-zone',
                'category' => 'ecommerce',
                'config'   => [
                    'layout'          => 'dashboard',
                    'primary_color'   => '#111827',
                    'secondary_color' => '#22d3ee',
                    'font_heading'    => 'Barlow',
                    'font_body'       => 'Barlow',
                    'button_radius'   => 'rounded-lg',
                    'hero_variant'    => 'image-left',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'compact',
                    'card_style'      => 'glass',
                    'footer_style'    => 'minimal',
                ],
            ],

            // ── Portfolio (6) ─────────────────────────────────────────────────
            [
                'name'     => 'Folio Noir',
                'slug'     => 'folio-noir',
                'category' => 'portfolio',
                'config'   => [
                    'layout'          => 'minimal',
                    'primary_color'   => '#0d0d0d',
                    'secondary_color' => '#ffffff',
                    'font_heading'    => 'Editorial New',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-none',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'minimal',
                ],
            ],
            [
                'name'     => 'Luminary',
                'slug'     => 'luminary',
                'category' => 'portfolio',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#c8a96e',
                    'secondary_color' => '#f5f0e8',
                    'font_heading'    => 'Canela',
                    'font_body'       => 'Lato',
                    'button_radius'   => 'rounded-full',
                    'hero_variant'    => 'image-left',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'Canvas Pro',
                'slug'     => 'canvas-pro',
                'category' => 'portfolio',
                'config'   => [
                    'layout'          => 'grid',
                    'primary_color'   => '#b5a99a',
                    'secondary_color' => '#2d2d2d',
                    'font_heading'    => 'Freight Display',
                    'font_body'       => 'Source Serif Pro',
                    'button_radius'   => 'rounded-sm',
                    'hero_variant'    => 'image-right',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'normal',
                    'card_style'      => 'outline',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'Pixel Frame',
                'slug'     => 'pixel-frame',
                'category' => 'portfolio',
                'config'   => [
                    'layout'          => 'contemporary',
                    'primary_color'   => '#0033ff',
                    'secondary_color' => '#ff2d78',
                    'font_heading'    => 'Neue Haas Grotesk',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-none',
                    'hero_variant'    => 'video',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'compact',
                    'card_style'      => 'glass',
                    'footer_style'    => 'minimal',
                ],
            ],
            [
                'name'     => 'Studio One',
                'slug'     => 'studio-one',
                'category' => 'portfolio',
                'config'   => [
                    'layout'          => 'classic',
                    'primary_color'   => '#f8f8f8',
                    'secondary_color' => '#334155',
                    'font_heading'    => 'Playfair Display',
                    'font_body'       => 'Nunito',
                    'button_radius'   => 'rounded-md',
                    'hero_variant'    => 'split',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'normal',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'Persona',
                'slug'     => 'persona',
                'category' => 'portfolio',
                'config'   => [
                    'layout'          => 'editorial',
                    'primary_color'   => '#e8d5d0',
                    'secondary_color' => '#5c7a5e',
                    'font_heading'    => 'DM Serif Display',
                    'font_body'       => 'DM Sans',
                    'button_radius'   => 'rounded-xl',
                    'hero_variant'    => 'carousel',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'stacked',
                ],
            ],

            // ── Agency (6) ────────────────────────────────────────────────────
            [
                'name'     => 'Velocity Agency',
                'slug'     => 'velocity-agency',
                'category' => 'agency',
                'config'   => [
                    'layout'          => 'contemporary',
                    'primary_color'   => '#0a0a0a',
                    'secondary_color' => '#ffe600',
                    'font_heading'    => 'Neue Montreal',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-none',
                    'hero_variant'    => 'video',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'Boldline',
                'slug'     => 'boldline',
                'category' => 'agency',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#1a1a1a',
                    'secondary_color' => '#f5c518',
                    'font_heading'    => 'Anton',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-sm',
                    'hero_variant'    => 'image-left',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'compact',
                    'card_style'      => 'outline',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'Bureau Creative',
                'slug'     => 'bureau-creative',
                'category' => 'agency',
                'config'   => [
                    'layout'          => 'grid',
                    'primary_color'   => '#374151',
                    'secondary_color' => '#4f46e5',
                    'font_heading'    => 'Archivo',
                    'font_body'       => 'Archivo',
                    'button_radius'   => 'rounded-lg',
                    'hero_variant'    => 'carousel',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'normal',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'Stratosphere',
                'slug'     => 'stratosphere',
                'category' => 'agency',
                'config'   => [
                    'layout'          => 'minimal',
                    'primary_color'   => '#0050ff',
                    'secondary_color' => '#f0f4ff',
                    'font_heading'    => 'Satoshi',
                    'font_body'       => 'Satoshi',
                    'button_radius'   => 'rounded-xl',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'glass',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'The Agency',
                'slug'     => 'the-agency',
                'category' => 'agency',
                'config'   => [
                    'layout'          => 'classic',
                    'primary_color'   => '#2c2c2c',
                    'secondary_color' => '#c9a84c',
                    'font_heading'    => 'Freight Big',
                    'font_body'       => 'Source Sans Pro',
                    'button_radius'   => 'rounded-md',
                    'hero_variant'    => 'split',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'Nexus Studio',
                'slug'     => 'nexus-studio',
                'category' => 'agency',
                'config'   => [
                    'layout'          => 'dashboard',
                    'primary_color'   => '#0d2137',
                    'secondary_color' => '#a3e635',
                    'font_heading'    => 'Epilogue',
                    'font_body'       => 'DM Sans',
                    'button_radius'   => 'rounded-lg',
                    'hero_variant'    => 'image-right',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'normal',
                    'card_style'      => 'glass',
                    'footer_style'    => 'stacked',
                ],
            ],

            // ── Blog (5) ──────────────────────────────────────────────────────
            [
                'name'     => 'Inkwell',
                'slug'     => 'inkwell',
                'category' => 'blog',
                'config'   => [
                    'layout'          => 'editorial',
                    'primary_color'   => '#2d1b0e',
                    'secondary_color' => '#d4a96a',
                    'font_heading'    => 'Libre Baskerville',
                    'font_body'       => 'Georgia',
                    'button_radius'   => 'rounded-none',
                    'hero_variant'    => 'image-left',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'Chronicle',
                'slug'     => 'chronicle',
                'category' => 'blog',
                'config'   => [
                    'layout'          => 'magazine',
                    'primary_color'   => '#1a1a2e',
                    'secondary_color' => '#c0392b',
                    'font_heading'    => 'Playfair Display',
                    'font_body'       => 'Source Serif Pro',
                    'button_radius'   => 'rounded-sm',
                    'hero_variant'    => 'carousel',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'compact',
                    'card_style'      => 'outline',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'Thoughtspace',
                'slug'     => 'thoughtspace',
                'category' => 'blog',
                'config'   => [
                    'layout'          => 'minimal',
                    'primary_color'   => '#fafaf9',
                    'secondary_color' => '#292524',
                    'font_heading'    => 'Lora',
                    'font_body'       => 'Lora',
                    'button_radius'   => 'rounded-full',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'Perspective',
                'slug'     => 'perspective',
                'category' => 'blog',
                'config'   => [
                    'layout'          => 'grid',
                    'primary_color'   => '#111111',
                    'secondary_color' => '#ff5f1f',
                    'font_heading'    => 'Bebas Neue',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-md',
                    'hero_variant'    => 'image-right',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'normal',
                    'card_style'      => 'flat',
                    'footer_style'    => 'minimal',
                ],
            ],
            [
                'name'     => 'The Daily Note',
                'slug'     => 'the-daily-note',
                'category' => 'blog',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#1c1c1c',
                    'secondary_color' => '#ffd700',
                    'font_heading'    => 'DM Serif Display',
                    'font_body'       => 'DM Sans',
                    'button_radius'   => 'rounded-lg',
                    'hero_variant'    => 'split',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'compact',
                    'card_style'      => 'glass',
                    'footer_style'    => 'multi-column',
                ],
            ],

            // ── Restaurant (4) ────────────────────────────────────────────────
            [
                'name'     => 'Bistro Noir',
                'slug'     => 'bistro-noir',
                'category' => 'restaurant',
                'config'   => [
                    'layout'          => 'classic',
                    'primary_color'   => '#1a0a0a',
                    'secondary_color' => '#c9a84c',
                    'font_heading'    => 'Cormorant Garamond',
                    'font_body'       => 'Crimson Text',
                    'button_radius'   => 'rounded-none',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'Harvest Table',
                'slug'     => 'harvest-table',
                'category' => 'restaurant',
                'config'   => [
                    'layout'          => 'minimal',
                    'primary_color'   => '#b85c38',
                    'secondary_color' => '#f5e6d3',
                    'font_heading'    => 'Abril Fatface',
                    'font_body'       => 'Karla',
                    'button_radius'   => 'rounded-sm',
                    'hero_variant'    => 'image-left',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'normal',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'Savor',
                'slug'     => 'savor',
                'category' => 'restaurant',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#7b3f1e',
                    'secondary_color' => '#f4a261',
                    'font_heading'    => 'Josefin Sans',
                    'font_body'       => 'Josefin Sans',
                    'button_radius'   => 'rounded-md',
                    'hero_variant'    => 'image-right',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'outline',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'The Plated',
                'slug'     => 'the-plated',
                'category' => 'restaurant',
                'config'   => [
                    'layout'          => 'contemporary',
                    'primary_color'   => '#2d3436',
                    'secondary_color' => '#e17055',
                    'font_heading'    => 'Bodoni Moda',
                    'font_body'       => 'Poppins',
                    'button_radius'   => 'rounded-full',
                    'hero_variant'    => 'video',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'compact',
                    'card_style'      => 'glass',
                    'footer_style'    => 'minimal',
                ],
            ],

            // ── Education (4) ─────────────────────────────────────────────────
            [
                'name'     => 'EduPrime',
                'slug'     => 'edu-prime',
                'category' => 'education',
                'config'   => [
                    'layout'          => 'dashboard',
                    'primary_color'   => '#1d4ed8',
                    'secondary_color' => '#16a34a',
                    'font_heading'    => 'Plus Jakarta Sans',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-lg',
                    'hero_variant'    => 'split',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'normal',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'Scholar Hub',
                'slug'     => 'scholar-hub',
                'category' => 'education',
                'config'   => [
                    'layout'          => 'grid',
                    'primary_color'   => '#3730a3',
                    'secondary_color' => '#f59e0b',
                    'font_heading'    => 'Nunito',
                    'font_body'       => 'Nunito',
                    'button_radius'   => 'rounded-xl',
                    'hero_variant'    => 'carousel',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'outline',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'LearnSpace',
                'slug'     => 'learn-space',
                'category' => 'education',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#0f766e',
                    'secondary_color' => '#f8fafc',
                    'font_heading'    => 'Outfit',
                    'font_body'       => 'Outfit',
                    'button_radius'   => 'rounded-2xl',
                    'hero_variant'    => 'image-right',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'normal',
                    'card_style'      => 'flat',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'Campus Pro',
                'slug'     => 'campus-pro',
                'category' => 'education',
                'config'   => [
                    'layout'          => 'classic',
                    'primary_color'   => '#7f1d1d',
                    'secondary_color' => '#94a3b8',
                    'font_heading'    => 'Merriweather',
                    'font_body'       => 'Source Sans Pro',
                    'button_radius'   => 'rounded-md',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'multi-column',
                ],
            ],

            // ── Health (4) ────────────────────────────────────────────────────
            [
                'name'     => 'WellnessCore',
                'slug'     => 'wellness-core',
                'category' => 'health',
                'config'   => [
                    'layout'          => 'minimal',
                    'primary_color'   => '#4a7c59',
                    'secondary_color' => '#f0fdf4',
                    'font_heading'    => 'DM Serif Display',
                    'font_body'       => 'DM Sans',
                    'button_radius'   => 'rounded-full',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'MedVault',
                'slug'     => 'med-vault',
                'category' => 'health',
                'config'   => [
                    'layout'          => 'dashboard',
                    'primary_color'   => '#0369a1',
                    'secondary_color' => '#e2e8f0',
                    'font_heading'    => 'IBM Plex Sans',
                    'font_body'       => 'IBM Plex Sans',
                    'button_radius'   => 'rounded-md',
                    'hero_variant'    => 'image-left',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'compact',
                    'card_style'      => 'outline',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'Vitality',
                'slug'     => 'vitality',
                'category' => 'health',
                'config'   => [
                    'layout'          => 'contemporary',
                    'primary_color'   => '#15803d',
                    'secondary_color' => '#f97316',
                    'font_heading'    => 'Sora',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-xl',
                    'hero_variant'    => 'video',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'normal',
                    'card_style'      => 'glass',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'CareLink',
                'slug'     => 'care-link',
                'category' => 'health',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#7c3aed',
                    'secondary_color' => '#6ee7b7',
                    'font_heading'    => 'Nunito',
                    'font_body'       => 'Nunito',
                    'button_radius'   => 'rounded-2xl',
                    'hero_variant'    => 'split',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'centered',
                ],
            ],

            // ── Real Estate (4) ───────────────────────────────────────────────
            [
                'name'     => 'Prestige Realty',
                'slug'     => 'prestige-realty',
                'category' => 'real_estate',
                'config'   => [
                    'layout'          => 'classic',
                    'primary_color'   => '#0f2942',
                    'secondary_color' => '#b8860b',
                    'font_heading'    => 'Cormorant Garamond',
                    'font_body'       => 'Raleway',
                    'button_radius'   => 'rounded-none',
                    'hero_variant'    => 'image-left',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'OpenDoor Pro',
                'slug'     => 'opendoor-pro',
                'category' => 'real_estate',
                'config'   => [
                    'layout'          => 'grid',
                    'primary_color'   => '#f8fafc',
                    'secondary_color' => '#1e293b',
                    'font_heading'    => 'Plus Jakarta Sans',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-lg',
                    'hero_variant'    => 'carousel',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'normal',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'EstateMark',
                'slug'     => 'estate-mark',
                'category' => 'real_estate',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#1c1c1e',
                    'secondary_color' => '#b07d62',
                    'font_heading'    => 'Neue Montreal',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-sm',
                    'hero_variant'    => 'image-right',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'glass',
                    'footer_style'    => 'minimal',
                ],
            ],
            [
                'name'     => 'Keystone Homes',
                'slug'     => 'keystone-homes',
                'category' => 'real_estate',
                'config'   => [
                    'layout'          => 'minimal',
                    'primary_color'   => '#d6cfc4',
                    'secondary_color' => '#3d3d3d',
                    'font_heading'    => 'Playfair Display',
                    'font_body'       => 'Lato',
                    'button_radius'   => 'rounded-md',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'normal',
                    'card_style'      => 'outline',
                    'footer_style'    => 'centered',
                ],
            ],

            // ── Event (4) ─────────────────────────────────────────────────────
            [
                'name'     => 'Gala Pro',
                'slug'     => 'gala-pro',
                'category' => 'event',
                'config'   => [
                    'layout'          => 'contemporary',
                    'primary_color'   => '#3b0764',
                    'secondary_color' => '#eab308',
                    'font_heading'    => 'Cinzel',
                    'font_body'       => 'Lato',
                    'button_radius'   => 'rounded-full',
                    'hero_variant'    => 'video',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'glass',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'EventFlow',
                'slug'     => 'event-flow',
                'category' => 'event',
                'config'   => [
                    'layout'          => 'dashboard',
                    'primary_color'   => '#0f172a',
                    'secondary_color' => '#e11d48',
                    'font_heading'    => 'Space Grotesk',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-xl',
                    'hero_variant'    => 'carousel',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'compact',
                    'card_style'      => 'outline',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'Summit Events',
                'slug'     => 'summit-events',
                'category' => 'event',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#1e3a8a',
                    'secondary_color' => '#f97316',
                    'font_heading'    => 'Oswald',
                    'font_body'       => 'Roboto',
                    'button_radius'   => 'rounded-lg',
                    'hero_variant'    => 'split',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'normal',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'Festive',
                'slug'     => 'festive',
                'category' => 'event',
                'config'   => [
                    'layout'          => 'minimal',
                    'primary_color'   => '#db2777',
                    'secondary_color' => '#fde68a',
                    'font_heading'    => 'Paytone One',
                    'font_body'       => 'Nunito',
                    'button_radius'   => 'rounded-2xl',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'minimal',
                ],
            ],

            // ── Travel (3) ────────────────────────────────────────────────────
            [
                'name'     => 'Wanderlust',
                'slug'     => 'wanderlust',
                'category' => 'travel',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#7c2d12',
                    'secondary_color' => '#fb923c',
                    'font_heading'    => 'Abril Fatface',
                    'font_body'       => 'Source Sans Pro',
                    'button_radius'   => 'rounded-full',
                    'hero_variant'    => 'image-left',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'glass',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'Atlas Pro',
                'slug'     => 'atlas-pro',
                'category' => 'travel',
                'config'   => [
                    'layout'          => 'grid',
                    'primary_color'   => '#1a3a2a',
                    'secondary_color' => '#c8a96e',
                    'font_heading'    => 'Raleway',
                    'font_body'       => 'Open Sans',
                    'button_radius'   => 'rounded-md',
                    'hero_variant'    => 'carousel',
                    'nav_style'       => 'bordered',
                    'section_spacing' => 'normal',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'Journey Hub',
                'slug'     => 'journey-hub',
                'category' => 'travel',
                'config'   => [
                    'layout'          => 'contemporary',
                    'primary_color'   => '#0c4a6e',
                    'secondary_color' => '#e2c786',
                    'font_heading'    => 'Sora',
                    'font_body'       => 'Poppins',
                    'button_radius'   => 'rounded-xl',
                    'hero_variant'    => 'video',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'centered',
                ],
            ],

            // ── Beauty (3) ────────────────────────────────────────────────────
            [
                'name'     => 'Gloss Studio',
                'slug'     => 'gloss-studio',
                'category' => 'beauty',
                'config'   => [
                    'layout'          => 'minimal',
                    'primary_color'   => '#fce4ec',
                    'secondary_color' => '#ad1457',
                    'font_heading'    => 'Italiana',
                    'font_body'       => 'Raleway',
                    'button_radius'   => 'rounded-full',
                    'hero_variant'    => 'centered',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'flat',
                    'footer_style'    => 'centered',
                ],
            ],
            [
                'name'     => 'Velvet Salon',
                'slug'     => 'velvet-salon',
                'category' => 'beauty',
                'config'   => [
                    'layout'          => 'classic',
                    'primary_color'   => '#1e0a2e',
                    'secondary_color' => '#d4af7a',
                    'font_heading'    => 'Bodoni Moda',
                    'font_body'       => 'Didact Gothic',
                    'button_radius'   => 'rounded-none',
                    'hero_variant'    => 'image-right',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'normal',
                    'card_style'      => 'shadow',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'Bloom Beauty',
                'slug'     => 'bloom-beauty',
                'category' => 'beauty',
                'config'   => [
                    'layout'          => 'contemporary',
                    'primary_color'   => '#f9a8d4',
                    'secondary_color' => '#6b8f71',
                    'font_heading'    => 'Gilda Display',
                    'font_body'       => 'Nunito',
                    'button_radius'   => 'rounded-2xl',
                    'hero_variant'    => 'split',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'glass',
                    'footer_style'    => 'minimal',
                ],
            ],

            // ── Automotive (3) ────────────────────────────────────────────────
            [
                'name'     => 'AutoForge',
                'slug'     => 'auto-forge',
                'category' => 'automotive',
                'config'   => [
                    'layout'          => 'split',
                    'primary_color'   => '#0d0d0d',
                    'secondary_color' => '#dc2626',
                    'font_heading'    => 'Barlow Condensed',
                    'font_body'       => 'Barlow',
                    'button_radius'   => 'rounded-sm',
                    'hero_variant'    => 'video',
                    'nav_style'       => 'transparent',
                    'section_spacing' => 'compact',
                    'card_style'      => 'flat',
                    'footer_style'    => 'multi-column',
                ],
            ],
            [
                'name'     => 'DrivePro',
                'slug'     => 'drive-pro',
                'category' => 'automotive',
                'config'   => [
                    'layout'          => 'grid',
                    'primary_color'   => '#1a1a2e',
                    'secondary_color' => '#2563eb',
                    'font_heading'    => 'Rajdhani',
                    'font_body'       => 'Inter',
                    'button_radius'   => 'rounded-lg',
                    'hero_variant'    => 'carousel',
                    'nav_style'       => 'solid',
                    'section_spacing' => 'normal',
                    'card_style'      => 'outline',
                    'footer_style'    => 'stacked',
                ],
            ],
            [
                'name'     => 'Torque Studio',
                'slug'     => 'torque-studio',
                'category' => 'automotive',
                'config'   => [
                    'layout'          => 'contemporary',
                    'primary_color'   => '#18181b',
                    'secondary_color' => '#ea580c',
                    'font_heading'    => 'Exo 2',
                    'font_body'       => 'DM Sans',
                    'button_radius'   => 'rounded-none',
                    'hero_variant'    => 'image-left',
                    'nav_style'       => 'floating',
                    'section_spacing' => 'spacious',
                    'card_style'      => 'glass',
                    'footer_style'    => 'minimal',
                ],
            ],

        ];

        foreach ($themes as $theme) {
            Theme::updateOrCreate(
                ['slug' => $theme['slug']],
                [
                    'name'     => $theme['name'],
                    'category' => $theme['category'],
                    'config'   => $theme['config'],
                ]
            );
        }

        $this->command->info('Seeded ' . count($themes) . ' themes across ' . collect($themes)->pluck('category')->unique()->count() . ' categories.');
    }
}
